version: '3.1'

services:
  app:
    image: "sivic-app"
    build:
      context: ./app
      args:
        - http_proxy
        - https_proxy
    volumes:
      - ./app:/srv
    environment:
      - DATABASE_URL=postgres://app:app@db/app
      - NODE_ENV=development  
      - DETECTION_API  
      - STORYBOOK_PORT
    depends_on:
      - migrate

  srv:
    image: "sivic-app"
    volumes:
      - ./app:/srv
    command: wait-for-it db:5432 -- yarn srv start:dev
    environment:
      - DATABASE_URL=postgres://app:app@db/app
      - DETECTION_API
      - NODE_ENV=development
    depends_on:
      - migrate
    ports:
      - "${SERVER_PORT}:80"

  storybook:
    image: "sivic-app"
    volumes:
      - ./app:/srv
    command: yarn web storybook
    environment:
      - STORYBOOK_PORT
    ports:
      - "${STORYBOOK_PORT}:${STORYBOOK_PORT}"

  migrate:
    image: "sivic-app"
    volumes:
      - ./app:/srv
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    command: wait-for-it db:5432 -- yarn db-migrate up
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
