version: '3.7'

x-app: &app
  image: "${DOCKER_REGISTRY}/sivic-app"
  volumes:
    - ./app:/srv
  environment:
    - DATABASE_URL=postgres://app:app@db/app
    - NODE_ENV=development  
    - IMAGE_URL
    - DETECTION_API  
    - YARN_REGISTRY
    - STORYBOOK_PORT

services:
  app:
    <<: *app

  srv:
    <<: *app
    command: wait-for-it db:5432 -- yarn srv start:dev
    ports:
      - "${SERVER_PORT}:80"

  storybook:
    <<: *app
    command: yarn web storybook
    ports:
      - "${STORYBOOK_PORT}:${STORYBOOK_PORT}"

  migrate:
    <<: *app
    command: wait-for-it db:5432 -- yarn db-migrate up
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
